"""
A SECOND, independent 144-question benchmark set for the full RAG-backed pipeline, deliberately
non-overlapping with finetune/training/test_inference.py's CUBYZ_QUESTIONS (the set used by
rag_batch_test.py). That original set has effectively saturated the "easy" enumerable facts across
docs/, addon_creator/, and CUBYZ_DEVELOPER_JUDGMENT.md -- Prototype 7 reached 143/144 on it after
the 2026-07-20 re-chunking fixes. This set exists to test whether that result generalizes, by
drawing on parts of the knowledge base the original set never touched: the addon-creator engine
validation reference (default values, error messages, and website-vs-engine mismatches not asked
before), the addon-creator field-export reference (UI-to-zon mapping details), the raw addon
creation docs (biomes.md/blocks.md/items.md/models.md), game_mechanics.md/crafting.md's remaining
detail, CONTENT_SUGGESTIONS.md's art/SBB guidance, and multiplayer.md's hosting/security/add-on/
Discord-bot sections. Every answer below was verified directly against the raw source files in
pipeline/raw_cubyz_dataset/ (not against a crunched knowledge_base chunk, and not
against the website's own claims where the engine reference explicitly says the website differs)
before being added here.

Usage:
    python3 rag_batch_test_v2.py           # all 144 questions
    python3 rag_batch_test_v2.py 10        # first 10 only, for a quick smoke check
"""
import sys

from local_rag_chat import ask, load_index

CUBYZ_QUESTIONS_V2 = [
    # --- Addon Creator: Blocks, website export behavior (FIELD_REFERENCE.md) ---
    ("In Cubyz's Addon Creator, which texture slot index corresponds to the block's 'left' side?",
     "Index 5 -- up=0, bottom=1, front=2, back=3, right=4, left=5 (not alphabetical or form order)"),
    ("What does setting a Cubyz block's render mode to \"cubyz:ore\" trigger in the Addon Creator, and what else does it require?",
     "A separate .ore = {...} block with fixed vein params is generated, and it requires an item icon"),
    ("What two block boolean fields does the Cubyz Addon Creator omit entirely for ore blocks?",
     "Collide and Transparent"),
    ("How does the Cubyz Addon Creator convert a block's emitted/absorbed light color for export?",
     "Hex color is converted to an integer via parseInt(hex, 16); only emitted if non-default"),
    ("What does the \"heal\" touch mode do to the dps value for a Cubyz block's onTouch callback?",
     "It negates the dps value"),
    ("What does the \"decay\" onUpdate/onTick/onBreak hook type need, in Cubyz's Addon Creator?",
     "A replacement block plus a prevention setting"),
    ("What does the \"replace_block\" hook type need in Cubyz's Addon Creator?",
     "An auto-namespaced target block"),
    ("When is the .name field present in a Cubyz block's onInteract export from the Addon Creator?",
     "Only for the \"open_window\" interact type"),
    ("What's the difference between \"auto\" and manual drop selection for a Cubyz block in the Addon Creator?",
     "Auto exports as .{.items=.{.auto}} (drops the block itself); manual exports the specified item, auto-namespaced"),
    ("What happens if a Cubyz block has no item icon set in the Addon Creator?",
     "A matching item file is auto-generated, referencing the block via .block=\"{addon}:{id}\""),
    ("When is a Cubyz item's food value field emitted in the Addon Creator's export?",
     "Only if it's greater than 0"),
    ("How does the Cubyz Addon Creator generate an item's shading gradient from its material color?",
     "The base hex color is converted to HSL, then re-sampled at 5 lightness steps (0.22/0.38/0.52/0.72/0.88)"),
    ("When are a Cubyz item's material fields (durability, swingSpeed, etc.) emitted by the Addon Creator?",
     "Only if the item has the .material tag present"),
    ("How many ingredient slots does the Cubyz Addon Creator's recipe form support?",
     "Up to 4"),
    ("How does the Cubyz Addon Creator handle a recipe output count of exactly 1 in its export?",
     "The count prefix is omitted if the count is 1"),
    ("What two fields does the Cubyz Addon Creator combine a biome's surface and subsurface blocks into?",
     "One combined .ground_structure field; the stone layer is a separate .stoneBlock field"),
    ("What gates whether a Cubyz biome's cave-specific fields (density scale, radius factor, crystal frequency) are exported at all?",
     "Whether the \"Is Cave\" checkbox is checked"),
    ("How does the Cubyz Addon Creator handle a biome's five climate/humidity/zone/growth/elevation radio groups on export?",
     "All 5 groups' checked values are flattened into one combined .properties list, not kept separate"),
    ("What fields does a Cubyz \"simple_tree\" structure row need in the Addon Creator?",
     "log, leaves, top, height, height_variation, and leafRadius"),
    ("What fields does a Cubyz \"fallen_tree\" structure row need in the Addon Creator?",
     "log, top, and height"),
    ("What fields does an \"sbb\" structure row need in the Cubyz Addon Creator?",
     "structure and placeMode"),
    ("What happens to a Cubyz entity's tags block in the Addon Creator export if it has no tags?",
     "The tags block is omitted entirely"),
    ("What controls whether a companion \"_emission\" texture file gets bundled for a Cubyz particle addon?",
     "The \"has emission\" checkbox -- it doesn't write a field directly, it controls whether a companion emission texture file is bundled"),
    ("What additional field does a Cubyz particle's \"sphere\" spawn shape add in the Addon Creator, and where does its value come from?",
     ".radius, from the particleShapeRadius field"),
    ("What additional field does a Cubyz particle's \"cube\" spawn shape add in the Addon Creator?",
     ".size, from the particleShapeSize field"),
    ("What additional field does a Cubyz particle's \"direction\" spawn mode add in the Addon Creator?",
     ".direction = .{x, y, z}, from the particleDirX/Y/Z fields"),
    ("What two ID-handling conventions does the Cubyz Addon Creator apply almost everywhere?",
     "Namespace auto-prefixing (addonName: or cubyz: based on whether the ID matches something in the project) and ID sanitization (lowercased, stripped to [a-z0-9_])"),
    ("What does an explicit colon in a Cubyz Addon Creator ID input field do?",
     "It bypasses namespace auto-prefixing entirely"),
    ("What does clicking \"Export Full Addon\" do in the Cubyz Addon Creator?",
     "Calls exportFullAddon(), which walks every object in window.projectData and writes it out as .zig.zon files inside a zip"),
    ("How does the Cubyz Addon Creator import an existing addon?",
     "importExistingAddon() regex-parses the .zig.zon text of each file back into the same internal field names"),

    # --- Engine-side validation defaults & error messages (ENGINE_VALIDATION_REFERENCE.md) ---
    ("What does a Cubyz block's .blockHealth field default to in the engine if omitted?",
     "1"),
    ("What does a Cubyz block's .emittedLight field default to if omitted?",
     "0"),
    ("What does a Cubyz block's .absorbedLight field default to if omitted?",
     "0xffffff (16777215)"),
    ("What does a Cubyz block's .degradable field default to if omitted?",
     "false"),
    ("What is a Cubyz block's .selectionCapabilities field, and how is it set?",
     "Defaults to .always (any tool can select it); not exposed anywhere in the Addon Creator website UI, hand-edit only"),
    ("What does a Cubyz block's .replaceable field default to if omitted?",
     "false"),
    ("What does a Cubyz block's .transparent field default to if omitted?",
     "false"),
    ("What does a Cubyz block's .collide field default to, and what's notable about that default?",
     "true -- the default is \"does collide,\" the opposite of what leaving it unset might suggest"),
    ("What does a Cubyz block's .viewThrough field default to?",
     "false, but it's forced to true if transparent or alwaysViewThrough is true"),
    ("What does a Cubyz block's .friction field default to if omitted?",
     "20"),
    ("What does a Cubyz block's .bounciness field default to if omitted?",
     "0.0"),
    ("What does a Cubyz block's .density field default to if omitted, and how does that differ from the website?",
     "main.physics.airDensity (a named engine constant, not a literal number); the website form defaults to 1.2"),
    ("What does a Cubyz block's .terminalVelocity field default to if omitted?",
     "90"),
    ("What does a Cubyz block's .mobility field default to if omitted?",
     "1.0"),
    ("What does a Cubyz block's .allowOres field default to if omitted?",
     "false"),
    ("What are the engine's raw fallback values inside a Cubyz block's .ore sub-object, and how do they compare to the website's own ore defaults?",
     "veins=0, size=0, maxHeight=i32 max, minHeight=i32 min, density=0.5 -- very different from the website's hardcoded ore defaults (veins=4.5, size=20, maxHeight=-600, density=0.25)"),
    ("What happens if a Cubyz block's onInteract/onBreak/onUpdate/onTick callback is present but malformed?",
     "The engine logs \"Failed to load onX event for block {id}\" and falls back to a no-op"),
    ("What happens if a Cubyz block's onTouch callback is malformed?",
     "The engine logs \"Failed to load onTouch event for block {id}\" and falls back to a no-op"),
    ("How does a Cubyz block's .drops field handle an unknown item id in a drop entry?",
     "It's silently skipped (continue), not errored"),
    ("What are the two supported formats for an entry in a Cubyz block's .drops array?",
     "\"auto\" (drops the block itself) or \"{count} {item}\""),
    ("What does the engine actually check to decide whether a Cubyz item has a material, as opposed to what the Addon Creator checks?",
     "The engine checks whether .material is an object, not whether a .material tag is present -- these happen to be coupled by the website's own logic"),
    ("What does a Cubyz item's .block field default to if omitted?",
     "null"),
    ("What happens if a Cubyz item material's modifier id doesn't match a known modifier?",
     "The engine logs \"Couldn't find modifier with id '{id}'. Replacing it with 'durable'\" and substitutes the durable modifier"),
    ("What is a Cubyz \"procedural item,\" and can the Addon Creator website create one?",
     "A separate, more advanced system using weighted parameter matrices mapping material properties to tool stats; the website does not support it at all -- hand-edit only"),
    ("What symbolic pattern-matching feature does Cubyz's recipe system support that the Addon Creator website doesn't expose?",
     "{symbol} wildcards in item ids, for recipes that match families of items rather than one exact item -- hand-edit only"),
    ("What does a Cubyz biome's .stoneBlock field default to if omitted?",
     "\"cubyz:slate/smooth\""),
    ("What does a Cubyz biome's .fogDensity field default to, and what happens to it internally?",
     "1.0, then internally divided by 15.0*128.0"),
    ("What do a Cubyz biome's .roughness, .hills, .mountains, and .keepOriginalTerrain fields default to if omitted?",
     "0 each"),
    ("What does a Cubyz biome's .interpolation field default to if missing or invalid?",
     "\"square\""),
    ("What does a Cubyz biome's .caveSmoothness field default to, and is it exposed on the Addon Creator website?",
     "4.0, clamped to [0.00001, 4.0]; not exposed by the website form at all"),
    ("What does a Cubyz biome's .caveNoiseStrength field default to, and is it exposed on the website?",
     "8; not exposed by the Addon Creator website form"),
    ("What does a Cubyz biome's .caveRadiusFactor field default to if omitted?",
     "1, clamped to [-2, 2]"),
    ("What does a Cubyz biome's .crystals field default to if omitted?",
     "0"),
    ("What does a Cubyz biome's .soilCreep field default to, and how does that differ from the website?",
     "0.5; the website form's default is 1.0"),
    ("What happens if a Cubyz biome's minimum height is greater than its maximum height?",
     "The engine logs \"Biome {id} has invalid height range ({min}, {max})\""),
    ("What does a Cubyz biome's .smoothBeaches field default to if omitted?",
     "false"),
    ("Is a Cubyz biome's .rivers field exposed on the Addon Creator website?",
     "No, not exposed by the website form at all; it defaults to false"),
    ("What happens if a Cubyz biome's minRadius is greater than its maxRadius?",
     "The engine logs \"Biome {id} has invalid radius range ({min}, {max})\""),
    ("What happens if a Cubyz biome's minRadius is too small relative to the world's biome grid resolution?",
     "The engine logs \"Biome {id} has radius {r}, smaller than grid resolution...\""),
    ("What are Cubyz's .parentBiomes and .transitionBiomes biome fields used for, and are they exposed on the Addon Creator website?",
     "Sub-biome nesting and biome-transition-blending systems; entirely unexposed by the website, hand-edit only"),
    ("What does a Cubyz entity model's .model field default to if omitted, and does the engine log an error?",
     "null, and no error is logged"),
    ("What special tag exists for Cubyz entity models that isn't exposed by the Addon Creator website form?",
     "The playerModel tag, which registers the entity as a selectable player skin"),
    ("How does the Cubyz engine resolve an entity's default texture file path?",
     "It splits the value on ':' and resolves the path as {assetFolder}/{mod}/entity_models/textures/{name}.png, falling back to assets/{mod}/entity_models/textures/{name}.png if the first doesn't exist"),
    ("What happens if a Cubyz particle's emission texture frame count doesn't match its base texture's?",
     "The engine logs a frame-count-mismatch error"),
    ("What does a Cubyz particle's .rotationVelocity field default to if omitted?",
     "{min: 20, max: 60}"),
    ("What does a Cubyz particle's .density field default to if omitted?",
     "{min: 2, max: 3}"),
    ("What does a Cubyz particle's .dragCoefficient field default to if omitted?",
     "{min: 0.5, max: 0.6}"),
    ("Is a Cubyz particle's .loopTime field exposed on the Addon Creator website?",
     "No, not exposed by the website form at all"),
    ("What does a Cubyz particle's .speed field default to if omitted?",
     "{min: 1, max: 1.5}"),
    ("What does a Cubyz particle's .lifeTime field default to if omitted?",
     "{min: 0.75, max: 1}"),
    ("What does a Cubyz particle's .randomRotate field default to if omitted?",
     "true (though this rarely applies in practice since the website always writes an explicit value)"),
    ("What happens if a Cubyz particle's .mode field has an invalid string value?",
     "The engine logs \"Error while parsing direction mode\" and falls back to \"spread\""),
    ("What does a Cubyz particle's .direction field default to if omitted?",
     "A Vec3f of {0, 0, 1}"),
    ("What happens if a Cubyz particle's .shape field has an invalid string value?",
     "The engine logs \"Error while parsing particle spawn data\" and falls back to a point shape"),
    ("What's the structural difference between a Cubyz particle's type-level properties and its emitter-level properties, in terms of when they're validated?",
     "Type properties (.texture/.rotationVelocity/.density/.dragCoefficient) are validated once, at registration time when the addon loads; emitter properties (.speed/.lifeTime/.shape/.mode/.direction) are parsed separately whenever something actually spawns the particle -- so a broken emitter field won't error at world-load time, only when triggered in-world"),
    ("What's the overall precedence rule when Cubyz's Addon Creator website and the game engine disagree on a field name or default?",
     "The engine is the source of truth, not the website -- the website is a convenience tool that can have bugs"),

    # --- FAQ / README ---
    ("What setting should you try lowering if Cubyz is lagging, per the FAQ?",
     "\"LOD Distance\" -- you'll only see a difference in the detail of distant chunks"),
    ("What should you do if compiling Cubyz keeps running for more than 10 minutes without doing anything?",
     "Kill and restart the process; deleting the zig-cache folder might also help"),
    ("What three unique features does Cubyz's top-level README highlight?",
     "Level of Detail (far view distances), 3D Chunks (no height or depth limit), and Procedural Crafting (infinite tool-crafting possibilities)"),
    # --- Addon docs: biomes.md/blocks.md/items.md/models.md ---
    ("What are the three valid Cubyz biome interpolation modes, and what does .smooth resolve to?",
     ".none, .linear, and .square; .smooth resolves to .square"),
    ("What is the minimum value for a Cubyz biome's interpolationWeight field?",
     "std.math.floatMin(f32) (default is 1)"),
    ("What does the keepOriginalTerrain field control for a Cubyz sub-biome?",
     "How much of the parent biome's terrain is preserved -- 1 means all of it, 0.5 means 50%"),
    ("What is Cubyz's default biome sky color, per the addon development documentation?",
     ".{0.46, 0.7, 1.0}"),
    ("What does the chance field default to for an entry in a Cubyz biome's parentBiomes list, if omitted?",
     "1"),
    ("What is the purpose of a Cubyz biome's isValidPlayerSpawn flag, per the addon docs?",
     "Ensures the player starts in a biome with trees"),
    ("What are the 15 valid values for a Cubyz biome's generation properties field?",
     "hot, temperate, cold; inland, land, ocean; wet, neitherWetNorDry, dry; barren, balanced, overgrown; mountain, lowTerrain, antiMountain"),
    ("What are Cubyz's 12 named block rotation modes?",
     "no_rotation, branch, carpet, direction, fence, hanging, ore, planar, sign, stairs, texture_pile, torch"),
    ("What is a Cubyz block's lodReplacement field for?",
     "Specifies a block used as a replacement at LOD1 and higher"),
    ("What is a Cubyz block's opaqueVariant field for?",
     "An opaque variant used at LOD0.5 and with the Leaves Quality option"),
    ("What does the hasBackface field control for a Cubyz block?",
     "Whether the block renders back faces"),
    ("What dimensions is a Cubyz block model's UV texture grid, and how many texture slots does it have?",
     "A 64x64 texture with 16 texture slots"),
    ("What coordinate-up convention does Cubyz use for its 3D block models?",
     "Z up"),
    ("What file format does Cubyz use for block models?",
     ".glb"),

    # --- Game mechanics / crafting / wiki homepage ---
    ("Besides being unable to heal, what can cause the Cubyz player to lose health?",
     "Fall damage and hazardous blocks such as cacti, lava, or magma"),
    ("What shape is Cubyz's health bar icon, per the wiki?",
     "An anatomical heart shape"),
    ("What shape is Cubyz's energy bar icon, per the wiki?",
     "A stomach shape"),
    ("How many energy bars does the Cubyz player have?",
     "8"),
    ("What happens to the Cubyz player's directional control while moving mid-air?",
     "It becomes much weaker"),
    ("How do you move an item from Cubyz's inventory into the hotbar?",
     "Left-click the item, drag it to the desired hotbar slot, then left-click again to place it"),
    ("How many stacks of items can Cubyz's bag slot hold, and how does that differ from a regular inventory slot?",
     "120 stacks -- unlike a regular slot, which holds up to 120 items of ONE stack, the bag slot holds multiple stacks"),
    ("What determines whether you can damage a Cubyz block at all, per the game mechanics page?",
     "If the block's resistance is higher than the damage you can deal, you're unable to damage it at all"),
    ("What two ways can you craft items in Cubyz, per the wiki?",
     "Via a Workbench or via the Crafting Menu"),
    ("What does Cubyz's Crafting Menu automatically show you?",
     "All possible items you can currently craft"),
    ("What qualifies an item to be usable for Workbench crafting in Cubyz?",
     "Any item considered a \"material\""),
    ("How far ahead can you see with Cubyz's Level of Detail system, per the wiki homepage?",
     "Up to 2400 blocks ahead"),
    ("What is the fourth \"Unique Feature\" listed on Cubyz's wiki homepage, alongside Level of Detail, 3D Chunks, and Procedural Crafting?",
     "Highly Optimized -- playable on low-end hardware"),

    # --- CONTENT_SUGGESTIONS.md: art & SBB guidelines ---
    ("What must you do before submitting a content suggestion for Cubyz on GitHub?",
     "Check it follows the Game Design Principles, make a reference implementation as an addon/mod/fork (no content from other games), follow the listed requirements, and open a PR or issue with screenshots"),
    ("How many colours does Cubyz recommend most block textures use?",
     "Roughly 4-6 colours"),
    ("What outline style do Cubyz item textures require, per the content guidelines?",
     "A full, coloured, 1-pixel outline, shaded so the top-left (lit) side is brighter and the bottom-right (shadow) side is darker"),
    ("How should a Cubyz item texture's contrast compare to its block counterpart?",
     "Items should have higher contrast than their block counterparts"),
    ("What should Cubyz block textures avoid, so they tile smoothly?",
     "Seams or repetitive patterns"),
    ("What must Cubyz Structure Building Blocks (SBBs) be filled with before saving, and why?",
     "cubyz:void blocks, unless you actually want the structure to replace surrounding terrain with air blocks"),
    ("What command must be used to convert degradable blocks like leaves and branches in a Cubyz SBB before saving?",
     "/toggledecay"),
    ("What guidance does Cubyz give for SBB structures that appear in bulk in the world?",
     "Split it into multiple randomized parts to avoid clearly visible repetition"),
    ("Why must Cubyz SBB structures account for what's underground, per the content guidelines?",
     "Structures often generate on a slope or above a cave, exposing their underside, so the structure should continue underground and include roots where applicable"),

    # --- Multiplayer: hosting, networking, security, add-ons, Discord bot ---
    ("What are Cubyz's two methods for hosting a multiplayer server?",
     "In-Game Hosting and Headless Setup (dedicated server)"),
    ("What's the main drawback of Cubyz's in-game hosting method?",
     "It requires you to keep your game running -- leaving the world or closing the game disconnects everyone else"),
    ("What two settings must be configured in launchConfig.zig to set up a Cubyz headless server?",
     ".headlessServer = true and .autoEnterWorld = <the world's name>"),
    ("What must already exist before you can set a Cubyz headless server to auto-enter a world?",
     "The world itself -- you must run the game in normal mode to create it first"),
    ("How do you find your machine's local gateway IP for Cubyz server port forwarding, on Linux?",
     "Run `ip route | grep default` (or `ip a`) and look for the Gateway IP"),
    ("What protocol should you select when configuring a Cubyz server's port-forward rule on your router?",
     "UDP"),
    ("How do you find a player's index/ID for Cubyz permission commands?",
     "Enable \"Show Player ID\" in the in-game Social tab, or as a server owner check the players folder inside the world save directory"),
    ("What three server-hardening options does Cubyz's multiplayer guide suggest against DDoS/exposure risk?",
     "Use a VPS, use a domain name with a proxy service like Cloudflare, or route traffic through a relay/VPS proxy"),
    ("Where can you download Cubyz add-ons, per the multiplayer guide?",
     "The official Discord's #addons-mods channel, or the community asset marketplace at addons.ashframe.net"),
    ("What happens when you install add-ons on a Cubyz dedicated server?",
     "They automatically sync and download for connecting players"),
    ("What does Cubyz's Mercur Discord bot do?",
     "Provides bi-directional chat communication between your Discord server and your Cubyz server, and can transmit server status to the Cubyz Server List"),
    ("What happens if Mercur's config.json file isn't found the first time you run the bot?",
     "The bot automatically generates one, then exits"),
    ("What command installs and runs Mercur, Cubyz's Discord relay bot?",
     "npx cubyz-discord-relay@latest (or @2.4.3 specifically for Cubyz 0.0.0)"),
    ("Per Cubyz's permission_layer.md, what does whitelisting a permission path grant?",
     "Access to that path AND all of its children in the tree -- e.g. whitelisting /command lets a user run every command"),
    ("If you whitelist /command but blacklist /command/spawn for a Cubyz user, what happens?",
     "They can run every command except /spawn"),

    # --- More engine validation & field reference (rounding out to 144) ---
    ("What happens if a Cubyz block's tags list ends up empty after processing, per the engine validation reference?",
     "The engine logs \"Block {id} is missing 'tags' field\" -- every block needs at least one tag"),
    ("What is Cubyz's blocks.zig register() function's fallback when a referenced block id can't be found, regardless of which field referenced it?",
     "Logs \"Couldn't find block {id}. Replacing it with air...\" and substitutes air -- it never crashes"),
    ("What Cubyz function is responsible for parsing a block's drop entries, per the engine validation reference?",
     "loadBlockDrop()"),
    ("What Zig function registers a Cubyz particle type, per the engine validation reference?",
     "register() in particles.zig"),
]


def main():
    limit = None
    for a in sys.argv[1:]:
        if a.isdigit():
            limit = int(a)
    questions = CUBYZ_QUESTIONS_V2[:limit] if limit else CUBYZ_QUESTIONS_V2

    index = load_index()

    for i, (q, expected) in enumerate(questions, 1):
        print(f"\n{'=' * 70}\n[{i}/{len(questions)}] Q: {q}\n{'=' * 70}")
        answer = ask(q, index, verbose=True)
        print(f"A: {answer}")
        print(f"   [expected: {expected}]")

    print(f"\n\n[~] Done -- {len(questions)} questions (second, independent benchmark set, "
          f"non-overlapping with rag_batch_test.py's CUBYZ_QUESTIONS).")


if __name__ == "__main__":
    main()
